
<?php
	$request = $this->getRequest()->getPost();
	$item = Mage::getModel('order/order')->load($request['id'])->_data;
?>

<div id="reman_order" style="top:-20px;">

        	<div id="details-order-baloon">How would you like it done?</div>
            
            <div id="vehicle_info" class="check-top-blocks" style="height: 362px;">
                <div class="title"><span>Vehicle info</span></div>
                <table style="margin-left:60px;">
                        <tr>
                            <td class="label">Year:</td>
                            <td><?php echo $item['year']; ?></td>
                        </tr>
                        <tr>
                            <td class="label">Make:</td>
                            <td><?php echo $item['make']; ?></td>
                        </tr>
                        <tr>
                            <td class="label">Model:</td>
                            <td><?php echo $item['model']; ?></td>
                        </tr>
                        <tr>
                            <td class="label">Engine:</td>
                            <td><?php echo $item['engine']; ?></td>
                        </tr>
                        <tr>
                            <td class="label">Drive:</td>
                            <td><?php echo $item['drive']; ?></td>
                        </tr>
                         <tr>
                            <td class="label">Serial #:</td>
                            <td><?php echo $item['serial']; ?></td>
                        </tr>
                         <tr>
                            <td class="label">Alt Part #:</td>
                            <td><?php echo $item['alt_partnum']; ?></td>
                        </tr>
                        <tr>
                            <td class="label">Notes:</td>
                            <td></td>
                        </tr>
                </table>
                <div style="clear:both"></div>
                <table class="vin" style="margin-left:35px;">
                    <tr>
                        <td class="label">VIN:</td>
                        <td> <?php echo $item['vin']; ?> </td>
                    </tr>
                    <tr>
                        <td class="label">Mileage:</td>
                        <td> <?php echo $item['mileage']; ?> </td>
                    </tr>
                    <tr  id="check-application-block">
                        <td class="label">Application:</td>
                        <td> <?php 
									if($item['commercial_app']){
										echo 'Commercial';
									}else{
										echo 'Non Commercial';
									}
								?> 
                        </td>
                    </tr>
                    
                </table>
            </div>
            
            <div id="order_details" class="check-top-blocks" style="height:100%;">
                <div class="title"><span>Order Details</span></div>
                           
                <table>
                     <tr>
                        <td class="label">Order Type:</td>
                        <td><?php echo $request['order_type']; ?></td>
                    </tr>
                     <tr>
                        <td class="label"> Web Order ID:</td>
                        <td><?php echo $request['id']; ?></td>
                    </tr>
                    <tr>
                        <td class="label"> Paradox ID:</td>
                        <td><?php echo $request['ete_order_id']; ?></td>
                    </tr>
                    <tr>
                        <td class="label"> CSI #:</td>
                        <td><?php echo $request['csi']; ?></td>
                    </tr>
                     <tr>
                        <td class="label"> Status:</td>
                        <td>
							<?php echo $item['order_status'];?>
                       </td>
                    </tr>
                    <tr>
                        <td class="label">Product Name:</td>
                        <td><?php echo $item['product_name']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Part Num:</td>
                        <td><?php echo $item['partnum']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Family:</td>
                        <td><?php echo $item['family']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Total Price:</td> 
                        <td><?php echo $item['total_amount']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Deposit Received:</td> 
                        <td><?php echo $item['deposit_received']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Original Invoice:</td> 
                        <td><?php echo $item['original_invoice']; ?></td>
                    </tr>    
                    <tr>
                        <td class="label">Return Auth #:</td> 
                        <td><?php echo $item['return_auth']; ?></td>
                    </tr>                          
                </table>
                <div style="clear:both"></div>
                <table class="vin" style="margin-top:7px;">
                    <tr>
                        <td class="label">PO #:</td>
                        <td><?php echo $item['po']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Claim #:</td>
                        <td><?php echo $item['claim']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">RO #:</td>
                        <td><?php echo $item['ro']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">End User Name:</td>
                        <td><?php echo $item['end_username']; ?></td>
                    </tr>
                </table>
            </div>
            <div id="sold-to" style="margin-top:25px;" class="check-bottom-blocks">
                <div class="title"><span>Sold To</span></div>
                <table class="vin" style="margin-left:10px;">
                    <tr style="height:20px;">
                        <td class="label">Customer Name:</td>
                        <td><?php echo $item['so_cust_name']; ?></td>
                    </tr>
                    <tr style="height:20px;">
                        <td class="label">Contact Name:</td>
                        <td><?php echo $item['so_cont_name']; ?></td>
                    </tr>
                    <tr style="height:20px;">
                        <td class="label">Phone:</td>
                        <td><?php echo $item['so_phone']; ?></td>
                    </tr>
                </table>
            </div>
         		 
                
                
            
            <div id="ship-to" style="margin-top:25px; height:100%;" class="check-bottom-blocks">
                <div class="title"><span>Ship To</span></div>
                
                <table class="vin" style="margin-left:10px;">
                    <tr>
                    	<td class="label">Customer Number:</td>
                        <td><?php echo $item['st_cust_num']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Customer Name:</td>
                        <td><?php echo $item['st_cust_name']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Contact Name:</td>
                        <td><?php echo $item['st_cont_name']; ?></td>
                    </tr>
                    <tr>
                        <td class="label">Phone:</td>
                        <td><?php echo $item['st_phone']; ?>  <?php  if($item['st_phone_ext'] != NULL){ echo "Ext.".$item['st_phone_ext']; } ?></td>
                        
                    </tr>
                    <tr>
                        <td class="label">Adress:</td>
                        <td>
							<?php echo $item['st_addr1']; ?> <br /> 
							<?php echo $item['st_addr2']; ?>
                        </td>
                    </tr>
                
                    <tr>
                        <td class="label">City:</td>
                        <td><?php echo $item['st_city']; ?></td>
                     </tr>   
                     <tr>
                        <td class="label">State:</td> 
                        <td><?php echo $item['st_state']; ?></td>
                     </tr>
                    <tr> 
                        <td class="label">ZIP:</td>   
                        <td id="check-st_zip"><?php echo $item['st_zip']; ?></td>
                    </tr>
                    
                    <tr>
                    	<td class="label">Carrier:</td>
                        <td><?php echo $item['carrier']; ?></td>
                    </tr>
                    <tr>
                    	<td class="label">Carrier Service</td>
                        <td><?php echo $item['carrier_service']; ?></td>
                    </tr>
                    <tr>
                    	<td class="label">Carrier Options</td>
                        <td><?php echo $item['carrier_options']; ?></td>
                    </tr>
                    <tr>
                    	<td class="label">Ship By Date</td>
                        <td><?php echo $item['date_ship']; ?></td>
                    </tr>
                    <tr>
                    	<td class="label">Deliver By Date</td>
                        <td<?php echo $item['date_deliver']; ?>></td>
                    </tr>
                    <tr>
                    	<td class="label">Ship From</td>
                        <td<?php echo $item['ship_from']; ?>></td>
                    </tr>
                    <tr>
                    	<td class="label">Tracking #</td>
                        <td><?php echo $item['tracknum']; ?></td>
                    </tr>
                </table> 
                
    </div>
            
           
			 <div class="clearer"></div>
            <div id="check-notes">
             <table>
             	
                    <tr>
                        <td class="label">Fluid:</td>
                        <td  style="font-weight:bold;"> <?php echo $item['fluid']; ?> </td>
                    </tr>
             
                <tr>
                <?php 
					// Warranty Array
					$warrantyArray = Mage::getModel('warranty/warranties')->getWarrantiesArray();
					foreach($warrantyArray as $index){
						if( $index['value'] == $item['warranty_id']){
							$warrantyLable = $index['label'];
						}
					}
				?>
                
                	<td class="label">Warranty:</td>
                    <td  style="font-weight:bold;"><?php echo $warrantyLable; ?></td>
                </tr>
                <tr>
                	<td class="label">Order Notes:</td>
                    <td  style="font-weight:bold;"><?php echo $item['order_notes']; ?></td>
                </tr>
                
             </table>
             
           </div>
</div>
