<?php 
	/**
	 * Reman Profile Template
	 *
	 * @category    Reman
	 * @package     Design
	 * @author		Igor Zhavoronkin (zhavoronkin.i@gmail.com)
	 */
?>
 
<?php 
	/* Get Companies Customers*/
	$result = Mage::helper('company')->getCompanyCustomers();

	/* Define action URL */
	$action = Mage::getUrl('profile/index');
	
?>	

<div id="remaqn_users_cont" style="display:none; top: -20px; position: relative;">
	<div class="heading"><span>Manage Users</span></div>
 <?php if (Mage::helper('customer')->isCompanyAdminUser()): ?>    
    
	<?php if (count($result) == 0): ?>
        <span>No records found</span>
	<?php endif; ?>
    <?php if (count($result) > 0): ?>
        <table class="reman_users_table">
            <tr>
                <td class="lable">First name</td>
                <td class="lable">Last name</td>
                <td class="lable">User e-mail</td>
                <td class="lable">Status</td>
                <td class="lable"></td>
            </tr>
			<?php  foreach($result as $key => $value): ?>
                 <?php if ($value['group_id'] != 6): ?>
					<?php 
                         /**
                            Define selected user ID
                         */
                        $selectedUserID =  $value['entity_id'];
					
                    ?>
                    <tr>
                        <td><?php echo $value['firstname'] ?></td>
                        <td><?php echo $value['lastname'] ?></td>
                        <td><?php echo $value['email'] ?></td>
                        <td>
                        	<?php 
									if ($value['group_id'] == 7){
										echo 'Disabled';
									}else{
										echo 'Active';
									}
							?>	
                                
                        
                        </td>
                         <td class="activate_links">
                            <a class="ac_Deactivate" <?php if ($value['group_id'] == 7): ?>style="display:none" <?php endif; ?> onclick=" manageUserAccount('<?php echo $action.'disable'; ?>', <?php echo $selectedUserID ?> , this); return false;">Deactivate</a>
                            
                            <a class="ac_Activate" <?php if ($value['group_id'] == 1): ?>style="display:none" <?php endif; ?> onclick=" manageUserAccount('<?php echo $action.'enable' ?>', <?php echo $selectedUserID ?> , this); return false;">Activate</a>
                            
                            
                        </td>
                        
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>    
	<?php endif; ?>
    <div class="add_new_user_link"></div>
<?php endif; ?>
<div id="session_error_popup_profile">
    <span>Sorry, your current session has expired. Please login again</span>
    <button onclick="window.location.href = '<?php echo Mage::getUrl('customer/account/login'); ?>'; return false;">OK</button>
</div> 
</div>

<div id="reman_users_orders" style="display:none; top: -20px; position: relative;">

	<div class="heading">
    
    	<span>Orders list</span>
    </div>
    
    <table id="grid" class="tablesorter">
		<thead>
            <tr>
           
                <th>Order WID/PID</th> 
                <th>Order Date</th> 
                <th>User Name</th>
                <th>PO#</th>
                <th>Year, Make, Model</th>
                <th>Part Number</th>
                <th>Order Status</th>
                <th></th>     
            </tr>
        </thead>
        <tbody>
        <?php  foreach(Mage::helper('order')->getCompanyOrdersIds() as $value): ?>
        
			 
            <?php if(count($value['orders']) != 0): ?> 
             	
                <?php  foreach($value['orders'] as $order): ?>
                <tr>	
                	<?php $item = Mage::getModel('order/order')->load($order)->_data; ?>
                        <!--Order ID-->
                        <td>
							<?php
                        		
								if($item['order_id'] != NULL){
									 echo $item['order_id']; 
								}else{
									echo '--/--';
								}
							?>	
							
                        </td>
                        <!--Order Date-->
                        <td><?php
									if($item['date_order'] != NULL){ 
										echo $item['date_order']; 
									}else{
										echo '--/--';
									}
							?>
                        </td>
                        <!--User Name-->
                        <td>
							<?php
								if($value['user_id'] != NULL){ 
									echo $value['user_id'];
								}else{
									echo '--/--';
								}
							?>
                        </td>
                        <!--#PO-->
                        <td class="po-value"><?php echo $item['po']; ?></td>
                        <!--YEAR/MAKE/MODEL-->
                        <td>
                            <?php echo $item['year']; ?>/
                            <?php echo $item['make']; ?>/
                            <?php echo $item['model']; ?>
                        </td>
                        <!-- Part Number-->
                        <td><?php echo $item['partnum']; ?></td>
                        <!-- Order Status-->
                        <td>
							<?php
								if($item['order_status'] != NULL){
									echo $item['order_status'];
								}else{
									echo 'New';
								}
							?>
                        </td>
                        
                        <td style="cursor:pointer; color:blue;" class="orders_ids" value="<?php echo $order; ?>">View</td>	
                     </tr>    
             	 <?php endforeach; ?>
             
             
					 <?php /*?><?php  foreach($value['orders'] as $order): ?>
                         <?php if ($order === reset($value['orders'])): ?>
                         <td style="cursor:pointer"  class="orders_ids" value="<?php echo $order; ?>"><?php echo $order; ?></td>
                         </tr>
                          <?php else: ?>
                            <tr>
                                <td></td>
                                <td style="cursor:pointer" class="orders_ids" value="<?php echo $order; ?>"><?php echo $order; ?></td>	
                            </tr>
                         <?php endif; ?>                
                    <?php endforeach; ?> <?php */?>
			<?php endif; ?>
           
         <?php endforeach; ?>
         </tbody>
    </table>
    
    
    <?php
				
				echo Mage::getModel('order/order')->getCollection()->addFieldToFilter('user_id', 'Igor Zhavoronkin');
	
	 ?>
    
</div>

<div id="reman_users_order_details" style="display:none;">
</div>

<div class="reman_preloader_order" style="display:none;"></div>

<script type="text/javascript">
	$j('.orders_ids').bind('click' , function(e){ 
		openOrder('<?php echo $action.'orderdetails';?>',$j(this).attr('value'));  
	});
	
	

	$j('.po-value').each(function(key,value){
		
		$j(this).html(jQuery.trim($j(value).html()).substring(0, 8).trim(this) + "...");
		
	});

	
	$j("#grid").tablesorter( {
			headers: {
					3: {sorter: false},
					4: { sorter: false}, 
					5: {sorter: false},
					6: { sorter: false},
					7: { sorter: false}
			}
	});
	
</script>

 