<?php 
	/**
	 * Reman Profile Template
	 *
	 * @category    Reman
	 * @package     Design
	 * @author		Igor Zhavoronkin (zhavoronkin.i@gmail.com)
	 */
?>
 
<?php 
	/* Get Companies Customers*/
	$result = Mage::helper('company')->getCompanyCustomers();
	/* Define action URL */
	$action = Mage::getUrl('profile/index');
	
?>	

<div id="remaqn_users_cont" style="display:none; top: -20px; position: relative;">
	<div class="heading"><span>Manage Users</span></div>
 <?php if (Mage::helper('customer')->isCompanyAdminUser()): ?>    
    
	<?php if (count($result) == 0): ?>
        <span>No records found</span>
	<?php endif; ?>
    <?php if (count($result) > 0): ?>
        <table class="reman_users_table">
            <tr>
                <td class="lable">First name</td>
                <td class="lable">Last name</td>
                <td class="lable">User e-mail</td>
                <td class="lable">Status</td>
                <td class="lable"></td>
            </tr>
			<?php  foreach($result as $key => $value): ?>
                 <?php if ($value['group_id'] != 6): ?>
					<?php 
                         /**
                            Define selected user ID
                         */
                        $selectedUserID =  $value['entity_id'];
					
                    ?>
                    <tr>
                        <td><?php echo $value['firstname'] ?></td>
                        <td><?php echo $value['lastname'] ?></td>
                        <td><?php echo $value['email'] ?></td>
                        <td>
                        	<?php 
									if ($value['group_id'] == 7){
										echo 'Disabled';
									}else{
										echo 'Active';
									}
							?>	
                                
                        
                        </td>
                         <td class="activate_links">
                            <a class="ac_Deactivate" <?php if ($value['group_id'] == 7): ?>style="display:none" <?php endif; ?> onclick=" manageUserAccount('<?php echo $action.'disable'; ?>', <?php echo $selectedUserID ?> , this); return false;">Deactivate</a>
                            
                            <a class="ac_Activate" <?php if ($value['group_id'] == 1): ?>style="display:none" <?php endif; ?> onclick=" manageUserAccount('<?php echo $action.'enable' ?>', <?php echo $selectedUserID ?> , this); return false;">Activate</a>
                            
                            
                        </td>
                        
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>    
	<?php endif; ?>
    <div class="add_new_user_link"></div>
<?php endif; ?>
<div id="session_error_popup_profile">
    <span>Sorry, your current session has expired. Please login again</span>
    <button onclick="window.location.href = '<?php echo Mage::getUrl('customer/account/login'); ?>'; return false;">OK</button>
</div> 
</div>

<div id="reman_users_orders" style="display:none; top: -20px; position: relative;">

	<div class="heading">
    
    	<span>Orders list</span>
    </div>
   
   <input id="po-input-search" style="padding:3px; width:100px;" type="text" placeholder="Search #PO" /> <button onclick="serchPO($j('#po-input-search').attr('value')); return false;" style="padding:3px;">Search</button>
    <button onclick="resetFilters(); return false;" style="padding:3px; position: relative; float: right;">Reset All</button>
   <select id="order-status-select" style="position: relative;float: right;margin-bottom: 10px;margin-right: 22px;" onchange="filterStatus($j('#order-status-select option:selected').html()); return false;">
   		<option>...</option>
        <option>Order</option>
        <option>Shipped</option>
        <option>Void</option>
   </select>
   
  
   <div style="position: relative;float: right; font-size: 12px; line-height: 21px; margin-right: 5px; font-weight: bold; margin-bottom:10px;">Filter by Order Status:</div>
    <table id="grid" class="tablesorter">
		<thead>
            <tr>
                <th>Order ID</th> 
                <th>Order Date</th> 
                <th>User Name</th>
                <th>PO#</th>
                <th>Year, Make, Model</th>
                <th>Part Number</th>
                <th>Order Status</th>
                <th></th>     
            </tr>
        </thead>
        <tbody>
        <?php  foreach(Mage::helper('order')->getCompanyOrdersIds() as $value): ?>
        
			 
            <?php if(count($value['orders']) != 0): ?> 
             	
                <?php  foreach($value['orders'] as $order): ?>
                <?php $item = Mage::getModel('order/order')->load($order)->_data; ?>
                <tr data-po="<?php echo $item['po']; ?>"  data-status="<?php
								if($item['order_status'] != NULL){
									echo $item['order_status'];
								}else{
									echo 'New';
								}
							?>">	
                	
                        <!--Order ID-->
                        <td>
							<?php
                        		
								if($item['order_id'] != NULL){
									 echo $item['order_id']; 
								}else{
									echo '--/--';
								}
							?>	
							
                        </td>
                        <!--Order Date-->
                        <td><?php
									if($item['date_order'] != NULL){ 
										echo $item['date_order']; 
									}else{
										echo '--/--';
									}
							?>
                        </td>
                        <!--User Name-->
                        <td>
							<?php
								if($value['user_id'] != NULL){ 
									echo $value['user_id'];
								}else{
									echo '--/--';
								}
							?>
                        </td>
                        <!--#PO-->
                        <td class="po-value"><?php echo $item['po']; ?></td>
                        <!--YEAR/MAKE/MODEL-->
                        <td>
                            <?php echo $item['year']; ?></br>
                            <?php echo $item['make']; ?></br>
                            <?php echo $item['model']; ?>
                        </td>
                        <!-- Part Number-->
                        <td><?php echo $item['partnum']; ?></td>
                        <!-- Order Status-->
                        <td class="order-status-field" >
							<?php
								if($item['order_status'] != NULL){
									echo $item['order_status'];
								}else{
									echo 'New';
								}
							?>
                        </td>
                        <td style="cursor:pointer; color:blue;" class="orders_ids" value="<?php echo $order; ?>">View</td>	
                     </tr>   
             	 <?php endforeach; ?>
			 <?php endif; ?>
         <?php endforeach; ?>
         </tbody>
    </table>
    <div id="no-match-results" style="display:none;">No Matchting Results</div>
</div>

<div id="reman_users_order_details" style="display:none;">
</div>

<div class="reman_preloader_order" style="display:none;"></div>

<script type="text/javascript">
	$j('.orders_ids').bind('click' , function(e){ 
		openOrder('<?php echo $action.'orderdetails';?>',$j(this).attr('value'));  
	});
	
	/* Trancate Long string for PO field*/
	$j('.po-value').each(function(key,value){
		if($j(value).html().length >8){
			$j(this).html(jQuery.trim($j(value).html()).substring(0, 10).trim(this) + "...");
		}
	});
	/* Init Sortable Table*/
	$j("#grid").tablesorter( {
			headers: {
					3: {sorter: false},
					4: { sorter: false}, 
					5: {sorter: false},
					6: { sorter: false},
					7: { sorter: false}
			}
	});
</script>

 