<?php
/**
 * Fake Home Page. Blank
 * Default Magento home page starts from Products Table. 
 * We need to redirect to login page from here.
 *
 * @category    Reman
 * @package     Design
 * @author		Igor Zhavoronkin (zhavoronkin.i@gmail.com)
 */
	if(!$this->helper('customer')->isLoggedIn()){
		Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getUrl('customer/account/login', $arguments= array()));
	}else{
		Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getUrl('quote', $arguments= array()));
	}
?>
