<?php
/**
 * Reman Product Inventory Template
 *
 * @category    Reman
 * @package     Design
 * @author		Igor Zhavoronkin (zhavoronkin.i@gmail.com)
 */ 
		$_product = Mage::getModel('sync/applic')->loadProduct($this->getRequest()->getPost('id')); 
		//MKE Stock
		$mke = $_product->getData('parts_inventory_nc');
		//BWI Stock
		$bwi = $_product->getData('parts_inventory_ne');
		//ONT Stock
		$ont = $_product->getData('parts_inventory_sw');
		//ATL Stock
		$atl = $_product->getData('parts_inventory_se');
		//DALLAS Stock
		$dal = $_product->getData('parts_inventory_sc');
		//IP
		$ip = $_product->getData('parts_inventory_ip');
		
		
		$array = array();
		
		if($bwi != 0 && $bwi != null){
			array_push($array, "21113");
		}
		
		array_push($array, "53223");
		
		if($ont != 0 && $ont != null){	
			array_push($array, "91761");
		}
		if($atl != 0 && $atl != null){	
			array_push($array, "30344");
		}
		
		if($dal != 0 && $dal != null){	
			array_push($array, "75261");
		}
		
		$SHIPPING_PRICE = 200;
		
?>
<!-- Stock Availability--> 
<div id="stock_avl">
	<div class="title">Pricing & Availability </div>
    
    <table id="ship-go-table" style="margin-bottom:25px;">
    	 <?php if(($atl != 0 || $atl != null) && ($ont != 0 || $ont != null) && ($bwi != 0 || $bwi != null) && ($mke != 0 || $mke != null) && ($ip != 0 || $ip != null) && ($dal != 0 || $dal != null)):?>
        <tr>
            <td>
            	<input id="zip_value" value="" type="text" placeholder="Destination Zip" />
            </td>
            <td>
            	<div id="estimate-shipping-btn"></div>
            </td>
        </tr>
        <?php endif; ?>
    </table>
    
    
    <table class="pricing">
    	
    	<tr>
        	<td class="lable">MSRP:</td>
            <td>$<?php echo number_format($_product->getData('parts_msrp'),2,'.','');?></td>
        </tr>
    	<tr>
        	<td class="lable">Your price:</td>
            <td>$<?php echo number_format($_product->getPrice(),2,'.','');?></td>
        </tr>
        
        <tr>
        	<td class="lable">Shipping:</td>
            <td><?php echo "$".number_format(Mage::helper('company')->getCustomerShippingPrice(),2,'.','');?></td>  
        </tr>
        
        
        
        <tr>
        	<td class="lable">Core Value:</td>
            <td>$<?php echo number_format($_product->getData('parts_core_price'),2,'.','');?></td>
        </tr>
        
        <tr style="height:40px;">
        	<td class="lable ship-from" style="display:none;">Your Total:</td>
            <td id="total-price-product-page" class="ship-from" style="display:none;"></td>
        </tr>
        
        
        <tr>
        	<td class="lable ship-from" style="display:none;">Ship From:</td>
            <td id="ship-from-value" class="ship-from" style="display:none;"></td>
        </tr>
        
        <tr>
        	<td class="lable">Availability:</td>
            <td style="width:100px;">
            	<?php
					if(($atl == 0 || $atl == null) && ($ont == 0 || $ont == null) && ($bwi == 0 || $bwi == null) && ($mke == 0 || $mke == null) && ($ip == 0 || $ip == null) && ($dal == 0 || $dal == null)){
						echo "Call for availability";
					}else{
						echo "Immediate";
					}
		?>
            </td>
        </tr>
        <tr>
        	<td class="lable ship-time" style="display:none;">Ship Time:</td>
            <td id="ship-time-value" class="ship-time" style="display:none;"></td>
        </tr>
    </table>
    <?php if(($atl != 0 || $atl != null) && ($ont != 0 || $ont != null) && ($bwi != 0 || $bwi != null) && ($mke != 0 || $mke != null) && ($ip != 0 || $ip != null) && ($dal != 0 || $dal != null)):?>
    <div style="display:none;" id="order-now-btn"></div>
     <?php endif; ?>
   
</div>

<script type="text/javascript">
	
	/* Enable jQuery Input PlaceHolders for IE*/
	initIEPlaceholders();
	
	//Estimate Shipping Event
	$j('#estimate-shipping-btn').click(function(){
		if($j("#zip_value").attr("value") != ""){
			estimateShipping(<?php echo json_encode($array); ?> , $j("#zip_value").attr("value"));
		}
	});
	// Load Order Page
	$j('#order-now-btn').click(function(){
		Reman_QuickQuote.prototype.loadOrder($j('#zip_value').attr('value'));
	});
	// Trigger Shipping estimation on Enter Button Event
	$j('#zip_value').keydown(function(event) {
	  if (event.which == 13) {
		 if($j("#zip_value").attr("value") != ""){
			estimateShipping(<?php echo json_encode($array); ?> , $j("#zip_value").attr("value"));
		}
	   }
	});
	
	
	var total = <?php echo $_product->getPrice();?> + <?php echo Mage::helper('company')->getCustomerShippingPrice();?>+<?php echo $_product->getData('parts_core_price');?>;
	
	$j('#total-price-product-page').html('$' + total+ '.00');
</script>

