<?php
/**
 * Reman Quick Quote Order Template
 *
 * @category    Reman
 * @package     Design
 * @author		Igor Zhavoronkin (zhavoronkin.i@gmail.com)
 */
?>

<?php 
	// Load Product Object	
	$_product = Mage::getModel('sync/applic')->loadProduct($this->getRequest()->getPost('id'));
	// Load Warranty Object
	
	//Product Type
	$partType = $_product->getName();
	 
	// Current Logged Company
	$company = Mage::helper('company')->getCustomerCompanyObject();
	// Load Current Logged Customer Object
	$customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
	$customer = Mage::getModel('customer/customer')->load($customer_id);
  	//state names
    $states = Mage::getModel('directory/country')->load('US')->getRegions();
	
	//Fluid Price
	$FlUIDE_PRICE = 5;
	
	//Fluid Amount
	$fliud_amount = $_product->parts_fluid_quantity;
	
	//Flued Options
	/*
	 * Parts Value: 7 = Required , 6 = Optional , 5 = None
	 * Company VAlue: R = Required , O = Optional , N = None
	 *
	*/
	if($_product->parts_fluid_option == 5){
		$fluid = 'N';
		$fliudPrice = 0;
	}else{
		$fluid = $company->fluid;
		
		if($fluid == "R"){
			$fliudPrice = $_product->parts_fluid_quantity * $FlUIDE_PRICE;
		}else if( $fluid == "O"){
			$fliudPrice = 0;
		}
	}
	
	// Calculated Base Warranty Id
	$warrantyId = Mage::helper('warranty')->getBaseWarrantyId($partType[0],$_product);
	//Get BaseWarrantyWeightID
	$warrantyWeightID = Mage::getModel('warranty/warranties')->getWarrantyWeight($warrantyId);
	// Parts Commercial Warranty ID
	$parts_commercial_warrantyId = $_product->getData('parts_commercial_warranty');
	// Parts Commercial Warranty Weight ID
	$parts_commercial_warranty_weightId = Mage::getModel('warranty/warranties')->getWarrantyWeight($parts_commercial_warrantyId);
	
	$warranties = Mage::helper('warranty')->getCalculatedWarrantyList($partType[0],$_product);
	
?>

<div id="reman_order">
    <form action="<?php echo $this->getUrl('quote/index/ordersubmit') ?>" method="post" id="form-order">
        
        <input type="hidden" name="data_order" value="<?php echo date("m.d.y");?>" />
        <input type="hidden" name="ete_cust" value="<?php echo Mage::helper('company')->getCompanyAdminEmail();?>" />
        <input type="hidden" name="aspiration" value="<?php echo $_product->getData('parts_aspiration'); ?>" />
        <input type="hidden" name="fuel" value="<?php echo $_product->getData('parts_fuel'); ?>" />
        <input type="hidden" name="cyl_type" value="<?php echo $_product->getData('parts_cylinder_type'); ?>" />
        <input type="hidden" name="unit_type" value="<?php echo $partType[0]; ?>" />
        
        <!-- Fluid Price-->
        <input type="hidden" id="fluid-amount" name="parts_amount" value="<?php echo $fliudPrice  ?>" />
        
        <!--Shipping-->
        <input type="hidden" name="ship_amount" id="shippingcost" value="" />
        <input type="hidden" name="carrier" id="shippingcarrier" value="" />
        <input type="hidden" name="carrier_service" id="shippingdays" value="" />
        
        <!--Total Amount-->
        <input type="hidden" id="total-price" name="total_amount" id="shippingdays" value="" />
        
        <div class="title">Order</div>
            
            <div id="vehicle_info">
                <div class="title">Vehicle info</div>
                <table>
                        <tr>
                            <td class="label">Year:</td>
                            <td><?php echo $this->getRequest()->getPost('year') ?></td>
                            <input type="hidden" name="year" value="<?php echo $this->getRequest()->getPost('year') ?>" />
                        </tr>
                        
                        <tr>
                            <td class="label">Make:</td>
                            <td><?php echo $this->getRequest()->getPost('make') ?></td>
                            <input type="hidden" name="make" value="<?php echo $this->getRequest()->getPost('make') ?>" />
                            
                        </tr>
                        <tr>
                            <td class="label">Model:</td>
                            <td><?php echo $this->getRequest()->getPost('model'); ?></td>
                            <input type="hidden" name="model" value="<?php echo $this->getRequest()->getPost('model'); ?>" />
                        </tr>
                        <tr>
                            <td class="label">Engine:</td>
                            <td><?php echo $this->getRequest()->getPost('engine'); ?>
                            <input type="hidden" name="engine" value="<?php  echo $this->getRequest()->getPost('engine'); ?>" />    
                            </td>
                        </tr>
                        <tr>
                            <td class="label">Drive:</td>
                            <td><?php 
									if($this->getRequest()->getPost('drive') == ""){
										$drive = $_product->getData('parts_drive');
									}else{
										$drive = $this->getRequest()->getPost('drive');
									}
									echo $drive;
								?>
                             
                             <input type="hidden" name="drive" value="<?php echo $drive; ?>" />     
                            </td>
                        </tr>
                        <tr>
                            <td class="label">Notes:</td>
                            <td></td>
                        </tr>
                </table>
                <div style="clear:both"></div>
                <table class="vin">
                    <tr>
                        <td class="label">VIN:</td>
                        <td><input type="text" name="vin" class="required-entry" /><em>*</em></td>
                    </tr>
                    <tr>
                        <td class="label">Mileage:</td>
                        <td><input type="text" name="mileage" class="required-entry" /><em>*</em></td>
                    </tr>
                </table>
                <table class="vin" style="margin-top:0px;">
                     <tr>
                        <td class="label">Commercial Application:</td>
                        <td><input id="commercial_app" type="checkbox" /></td>
                        <input id="commercial_app_value" type="hidden" name="commercial_app" value="N" />  
                    </tr>
                </table>
            </div>
            
            
            <div id="order_details">
                <div class="title">Order Details</div>
                            
                <div id="family_order">
                    <div class="lable">Family:</div>
                    <div class="value"><?php echo $_product->getData('parts_family'); ?></div>
                    <input type="hidden" name="family" value="<?php echo $_product->getData('parts_family'); ?>" />
                </div>
                <table>
                        <tr>
                            <td class="label">Product Name:</td>
                            <td><?php echo $_product->getName();?></td>
                        </tr>
                        
                        <tr>
                            <td class="label">Part Num:</td>
                            <td><?php echo $_product->getSku();?></td>
                            <input type="hidden" name="partnum" value="<?php echo $_product->getSku(); ?>" />
                            
                        </tr>
                        <tr>
                            <td class="label">Price:</td>
                            <td>$<?php echo number_format($_product->getPrice(),2,'.','');?></td>
                            <input type="hidden" id="part-price" name="unit_amount" value="<?php echo number_format($_product->getPrice(),2,'.','');?>" />
                        </tr>
                        <tr>
                            <td class="label">Core:</td>
                            <td>$<?php echo number_format($_product->getData('parts_core_price'),2,'.','');?></td>
                            <input type="hidden" id="core-price" name="core_amount" value="<?php echo number_format($_product->getData('parts_core_price'),2,'.','');?>" />
                        </tr>
                        <tr>
                            <td class="label">Shipping:</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td class="label">Tax:</td>
                            <td></td>
                        </tr>
                </table>
                <div style="clear:both"></div>
                <table class="vin">
                    <tr>
                        <td class="label">PO #:</td>
                        <td><input type="text" name="po" class="required-entry" /><em>*</em></td>
                    </tr>
                    <tr>
                        <td class="label">Claim #:</td>
                        <td><input type="text" name="claim" /></td>
                    </tr>
                    <tr>
                        <td class="label">RO #:</td>
                        <td><input type="text" name="ro" /></td>
                    </tr>
                    <tr>
                        <td class="label">End User Name:</td>
                        <td><input type="text" name="end_username" /></td>
                    </tr>
                </table>
            </div>
            
            
            <div id="sold-to" style="margin-top:25px;">
                <div class="title">Sold To</div>
                
                <table class="vin">
                    <tr>
                        <td class="label">Customer Name:</td>
                        <td><input type="text" name="so_cust_name" value="<?php echo $this->helper('company')->getCompanyName(); ?>" /></td>
                    </tr>
                    <tr>
                        <td class="label">Contact Name:</td>
                        <td><input type="text" name="so_cont_name" value="<?php echo $customer->getFirstname(); ?>"/></td>
                    </tr>
                    <tr>
                        <td class="label">Phone:</td>
                        <td><input type="text" name="so_phone" value="<?php echo $customer->phone; ?>" /></td>
                    </tr>
                    <tr>
                        <td class="label">Adress:</td>
                        <td><input type="text" name="adress_st" /></td>
                    </tr>
                    <input type="hidden" name="so_phone_ext" value="" />
                </table>
                
                <table class="adress">
                    <tr>
                        <td class="input-1"><input type="text" /></td>
                        <td style="padding-right:5px;">
                            <select id="sold-to-states" style="width:160px;">
                             <?php  foreach($states as $state): ?>
                                <option value="<?php echo $state->getId(); ?>"><?php echo $state->getName(); ?></option>
                             <?php endforeach; ?>   
                            </select>
                        </td>
                        <td class="input-zip"><input type="text" /></td>
                    </tr>
                </table>
            
            
            </div>
        
            
            <div id="ship-to" style="margin-top:25px;">
                <div class="title">Ship To</div>
                
                <table class="vin">
                    <tr>
                        <td class="label">Same as Sold To:</td>
                        <td><input id="same-as-sold" type="checkbox" /></td>
                    </tr>
                    <tr>
                        <td class="label">Customer Name:</td>
                        <td><input type="text" name="st_cust_name" class="required-entry" /><em>*</em></td>
                    </tr>
                    <tr>
                        <td class="label">Contact Name:</td>
                        <td><input type="text" name="st_cont_name" class="required-entry" /><em>*</em></td>
                    </tr>
                    <tr>
                        <td class="label">Phone:</td>
                        <td><input type="text" name="st_phone" class="required-entry" /><em>*</em></td>
                        <input type="hidden" name="st_phone_ext" value="" />
                    </tr>
                    <tr>
                        <td class="label">Adress:</td>
                        <td><input type="text" name="st_addr1" class="required-entry" /><em>*</em></td>
                        <input type="hidden" name="st_addr2" value="" />
                    </tr>
                </table>
                
                <table class="adress">
                    <tr>
                        <td class="input-1"><input name="st_city" type="text" /></td>
                        <td style="padding-right:5px;">
                            <select id="ship-to-states" style="width:135px;" onchange="$j('#st_state').attr('value', this.value); return false;" >
                               <?php  foreach($states as $state): ?>
                                 <option value="<?php echo $state->getId(); ?>"><?php echo $state->getName(); ?></option>
                               <?php endforeach; ?>   
                            </select>
                            <input id="st_state" type="hidden" name="st_state" value="" />
                        </td>
                        <td class="input-zip"><input name="st_zip" style="width:45px;" type="text" class="required-entry" /><em>*</em></td>
                    </tr>
                </table>
            
            </div>
            
            <?php if($partType[0] == 'T'): ?>	
                <div id="fuid-info">
                    <div class="title">Fluid</div>
                    <?php if($fluid == 'O'): ?>	
                        <div class="optional">
                            <span>Optional: </span><input onchange="calculateFluid(this.checked);" type="checkbox"  />
                        </div>
                    <?php endif; ?> 
                    
                     <?php if($fluid == 'R'): ?>	
                        <div class="text">
                            <span>Fluid Required</span>
                        </div>
                     <?php endif; ?>
                     
                     <?php if($fluid == 'N'): ?>	
                        <div class="text">
                            <span>No Fluid Required</span>
                        </div>
                     <?php endif; ?>
                </div>
             <?php endif; ?>
            
            <div id="warranty-info">
                <div class="title">Warranty</div>
                <select id="warrenty_select" onchange="$j('#order_warrenty').attr('value', $j('#warrenty_select option:selected').html()); return false;" >
                    <?php  foreach($warranties as $index): ?>
						 	 <option <?php if($index['weight'] == $warrantyWeightID): ?> selected="selected"  
							 <?php else: ?> 
                             <?php /*?>
								Display all warranties Names whose value 
								retrieved from the Warranty File is less than or equal to the BWV
								(calculated in (a))
							 <?php */?>
                             
                             <?php if ($index['weight'] > $warrantyWeightID || $index['weight'] == $parts_commercial_warranty_weightId  ):?>
                             	style="display:none;"
                             <?php endif; ?>   

							 <?php endif; ?>value="<?php echo $index['value'] ?>" weight="<?php echo $index['weight'] ?>"><?php echo $index['label'] ?></option>
                    <?php endforeach; ?>
                </select>
            	<input id="order_warrenty" type="hidden" name="warrenty_terms" value="" />
            </div>
            
            
            <div id="order-notes" style="margin-bottom:20px;">
                <div class="title">Order Notes</div>
                <textarea rows="3" cols="100" name="notes">
                </textarea>
            </div>
            
            <div class="buttons">
                <button type="reset" onclick="Reman_QuickQuote.prototype.resetOrder(); return false;">Cancel</button>
                <button type="submit">Submit Order</button>
            </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-order', true);
		
		// Parts Commercial Warranty value
		var comWarrantyId = <?php 
								if(!is_null($parts_commercial_warranty_weightId)){
									
									echo $parts_commercial_warranty_weightId;
								
								}else{
								
									echo 0;
								}
									
			
							 ?>;
		var baseWarrantyId = <?php echo $warrantyWeightID; ?>;
		var fluidAmount = <?php echo $fliud_amount; ?>;
		
    //]]>
		
		$j(document).ready(function(){
			// Set selected warrenty value on Order Load
			$j('#order_warrenty').attr('value', $j('#warrenty_select option:selected').html());
		
			// Set Shipping values
			$j('#shippingcost').attr('value',  window.truecost );
			$j('#shippingcarrier').attr('value', window.carrier );
			$j('#shippingdays').attr('value', window.servicedays );
			
			
			
			calculateTotalPrice();
			
			 
		});
		
		$j('#reman_order input').click(function(e){
			if($j(e.target).hasClass('validation-failed')){
				$j(e.target).removeClass('validation-failed');
			}
		});
		
		$j('#same-as-sold').click(function() {
			if($j(this).is(':checked')) {
				
				for( var i = 0; i<=$j('#sold-to input').length-1; i++){
					$j('#ship-to input')[i+1].value = $j('#sold-to input')[i].value;
				}
				
				for (var s = 0; s<=$j('#ship-to-states option').length; s++){
					if($j('#sold-to-states option:selected').val() == $j($j('#ship-to-states option')[s]).val() ){
						$j($j('#ship-to-states option')[s]).attr('selected','selected');
					}
				}
				
			} else {
				for( var i = 1; i<=$j('#ship-to input').length-1; i++){
					$j('#ship-to input')[i].value = "";
				}
				$j($j('#ship-to-states option')[0]).attr('selected','selected');
   	    	}
		});
		
		$j('#commercial_app').click(function(){
			if($j(this).is(':checked')){
				$j('#commercial_app_value').attr('value',"Y");
				
				/*
					iii. If the “Commercial Application” is checked AND the [Commwar] field is populated,
						 AND the retrieved Commwar value is less than the BWV, then the values retrieved form
						 the Warranty File become the BW and the BWV
				*/
				
				if(comWarrantyId == 0) return;
				
				if(comWarrantyId < baseWarrantyId){
					$j('#warrenty_select option').filter(function(index) {
							if($j(this).attr('weight') == comWarrantyId){
								$j(this).attr('selected','selected');
								$j(this).show();
							}
							if($j(this).attr('weight') > comWarrantyId){
								$j(this).hide();
							}
					});
				}
				
			}else{
				$j('#commercial_app_value').attr('value',"N");
				if(comWarrantyId == 0) return;
				if(comWarrantyId < baseWarrantyId){
					$j('#warrenty_select option').filter(function(index) {
							if($j(this).attr('weight') > baseWarrantyId){
								$j(this).hide();
							}else if($j(this).attr('weight') <= baseWarrantyId){
								$j(this).show();
							}
							
							if($j(this).attr('weight') == comWarrantyId){
								$j(this).hide();
							}
							
							if($j(this).attr('weight') == baseWarrantyId){
								$j(this).attr('selected','selected');
							}
					});
				}
				
			}
		});
		
		
		function calculateFluid(checked){
			if(checked){
			   var total = fluidAmount * 5;
			   $j('#fluid-amount').attr('value', total ); 
			}else{
			   $j('#fluid-amount').attr('value', 0 ); 
			}
		}
		
		// Calculate Total Amount
		
		function calculateTotalPrice(){
		
			var shippingPrice = Number(window.truecost);
			
			var fluidPrice = Number($j('#fluid-amount').attr('value'));
				
			var partPrice = Number($j('#part-price').attr('value'));
			
			var corePrice = Number($j('#core-price').attr('value'));
		
			var total  = shippingPrice + fluidPrice + partPrice + corePrice;
			
			 $j('#total-price').attr('value', total);	
		}
		
		
    </script>
</div>