<?php
/**
 * Reman Catalog
 * Ajax Product page template
 * @author Igor Zhavoronkin
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = Mage::getModel('sync/applic')->loadProduct($this->getRequest()->getPost('id')); ?>
<?php $_description = Mage::getModel('sync/applic')->loadProduct($this->getRequest()->getPost('id'))->getDescription(); ?>

<div class="product-view_quote">
    <div class="product-essential">
   
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">
 			
              <div class="product-img-box">
         
                   <p class="product-image">
                   	
                        <?php
							
                            $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->htmlEscape(Mage::getModel('catalog/product')->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                            echo $_helper->productAttribute($_product, $_img, 'image');
                        ?>
                    </p>
                    
             </div>
            
            	           
           <?php /*?> <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div><?php */?>
            
            <div id="general_info">
                  <table>
                        <tr>
                        	<td class="label">Part Number:</td>
                            <td><?php echo $_product->getData('sku'); ?></td>
                        </tr>
                        <tr>
                            <td class="label">Drive:</td>
                            <td><?php echo $_product->getData('parts_drive'); ?></td>
                        </tr>
                        <tr>
                            <td class="label">Year:</td>
                            <td><?php echo $_product->getData('parts_start_year'); ?></td>
                        </tr>
                        
                        <tr>
                            <td class="label">Fuel:</td>
                            <td><?php echo $_product->getData('parts_fuel'); ?></td>
                        </tr>
                        <tr>
                            <td class="label">Engine Sizes:</td>
                            <td><?php echo $_product->getData('parts_engine'); ?></td>
                        </tr>
                        <tr>
                            <td class="label">Aspiration:</td>
                            <td><?php echo $_product->getData('parts_aspiration'); ?></td>
                        </tr>
                        <tr>
                            <td class="label">Cylinder Type:</td>
                            <td><?php echo $_product->getData('parts_cylinder_type'); ?></td>
                   		</tr>
                </table>
               
            </div>
        </div>
        <div class="clearer"></div>
    </form>
 </div>

    <div class="product-collateral" style="margin-top:50px;">      
      	      <div style="clear:left">
              <div class="description_lable" style="font-size:15px;">Description:</div>
              <div class="desc_cont" style="font-size:12px; margin-left:10px;">
        <?php echo $this->helper('catalog/output')->productAttribute(Mage::getModel('sync/applic')->loadProduct($this->getRequest()->getPost('id')), $_description, 'description') ?>
				</div>
				<?php if(is_null($_product->getData('document_sellsheet')) == false || is_null($_product->getData('document_synthetecatf'))== false ): ?>
					<div class="description_lable" style="margin-top:25px; font-size:15px;">Documentation:</div>
					<div class="reman_docs">
					<?php if($_product->getData('document_sellsheet') != null): ?>	
						<a href="<?php echo Mage::getBaseUrl('media').'docs/'.$_product->getData('document_sellsheet') ?>" target="_blank"><?php echo $_product->getResource()->getAttribute('document_sellsheet')->getStoreLabel(); ?></a>
					<?php endif; ?>	
					<?php if($_product->getData('document_synthetecatf') != null ): ?>	
						<a href="<?php echo Mage::getBaseUrl('media').'docs/'.$_product->getData('document_synthetecatf') ?>" target="_blank"><?php echo $_product->getResource()->getAttribute('document_synthetecatf')->getStoreLabel();?></a>
					<?php endif; ?>	
					</div>
				<?php endif; ?>	
			</div>
    </div>
</div>