<?php
/**
 * Reman Quick Quote Template
 *
 * @category    Reman
 * @package     Design
 * @author		Igor Zhavoronkin (zhavoronkin.i@gmail.com)
 */
	if(!$this->helper('customer')->isLoggedIn()):
		Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getUrl('customer/account/login', $arguments= array()));
	 endif;
?>
<div id="steps">

<div id="welcome_bunner"></div>

<!-- First Step Quick quote (MAKE DATA)-->
<div id="breadcrumb_info"></div>
	<table id="steps_info">
    	<tr>
        	<td id="step_1" class="step_lable">STEP ONE:</td>
            <td id="step_1_message">How we can help you today?</td>
        </tr>
        <tr id="step_2_block" style="display:none;">
        	<td id="step_2" class="step_lable">STEP TWO:</td>
            <td id="step_2_message"></td>
        </tr>
    </table>


	<div id="table_container">
		<!--Preloader-->
        <div id="preloader_cont">
			<div id="reman_preloader"></div>
		</div>
        <!--Group Selects-->
        <div id="group_select"> 
            <div id="autotrans" class="cat_select" cat="T"></div>
             <!-- ADD class="cat_select" to enable !!!!!! -->
            <div id="transcase"  cat="X"></div>
        </div>
        <!--Make Selection-->
		<div id="make_tbl" style="display:none;">
			 <ul class="list_make">
				 <?php  foreach($this->getMake() as $index => $value): ?>
                    <li class="make_select"  value="<?php echo $value['make_id']?>" name="<?php echo $value['make']?>" startyear="<?php echo $value['start_year']?>" endyear="<?php echo $value['end_year']?>">
                        <img src="<?php echo $this->getSkinUrl('images/makes/'.$value['make'].'.png') ?>" alt="<?php echo $value['make'] ?>" />
                    </li>
                 <?php endforeach; ?>
			</ul>
		</div>
		<!--Year Selection-->
		<div id="year_tbl" style="display:none;">
		</div>   
		<!--Model Selection-->
		<div id="model_tbl" style="display:none;">
			<span class="label">Select Model:</span>
		</div>
		<!--Parts Selection-->
		<div id="parts_tbl" style="display:none;">
		</div>
        
        <div id="reman-product_info">
        </div>
		<div id="product_error_popup">
    		<span>Part number for selected configuration is not available.</span>
            <button onclick="$j('#product_error_popup').fadeOut();">OK</button>
    	</div> 
	</div>
    <!--Assistant Info -->
    <!--<div id="reman-invent_info" style="display:none;"></div>
	<div id="assis_info">
        <div class="banner"></div>
    	<span>For assistant with your Order or for any question you may have, please contanct our Customer Loyalty Team at 1-800-924-9479</span>
	</div>
    <div class="product_error"></div>-->
</div>