<?php
/**
 * Reman Quick Quote Template
 *
 * @category    Reman
 * @package     Design
 * @author		Igor Zhavoronkin (zhavoronkin.i@gmail.com)
 */
	if(!$this->helper('customer')->isLoggedIn()):
		Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getUrl('customer/account/login', $arguments= array()));
	 endif;
?>
<div id="steps">
<!-- First Step Quick quote (MAKE DATA)-->
<div id="breadcrumb_info"></div>
	<div id="table_container">
		<!--Preloader-->
        <div id="preloader_cont">
			<div id="reman_preloader"></div>
		</div>
        <!--Group Selects-->
        <div id="group_select">
        	 <span class="label">Select Category:</span>	
			 <ul class="list">
                    <li class="cat_select" cat="T">AUTO TRANSMISSION</li>
                    <li class="cat_select" cat="X">TRANSFER CASE</li>
             </ul>
        </div>
        <!--Make Selection-->
		<div id="make_tbl" style="display:none;">
			 <span class="label">Select Make:</span>	
			 <ul class="list">
			 <?php  foreach($this->getMake() as $index => $value): ?>
				<li class="make_select"  value="<?php echo $value['make_id']?>" startyear="<?php echo $value['start_year']?>" endyear="<?php echo $value['end_year']?>">
					<?php echo $value['make'] ?>
				</li>
			<?php $index +=1 ?>
			<?php if($index%25 == 0 && $index != 0): ?>
			</ul>
			<ul class="list">
			<?php endif; ?>			
			<?php endforeach; ?>
		
		</div>
		<!--Year Selection-->
		<div id="year_tbl" style="display:none;">
			<span class="label">Select Production Year:</span>
		</div>   
		<!--Model Selection-->
		<div id="model_tbl" style="display:none;">
			<span class="label">Select Model:</span>
		</div>
		<!--Parts Selection-->
		<div id="parts_tbl" style="display:none;">
		</div>
        
        <div id="reman-product_info">
        </div>
		<div id="product_error_popup">
    		<span>Part number for selected configuration is not available.</span>
            <button onclick="$j('#product_error_popup').fadeOut();">OK</button>
    	</div> 
	</div>
    <!--Assistant Info -->
    <div id="reman-invent_info" style="display:none;"></div>
	<div id="assis_info">
        <div class="banner"></div>
    	<span>For assistant with your Order or for any question you may have, please contanct our Customer Loyalty Team at 1-800-924-9479</span>
	</div>
    <div class="product_error"></div>
</div>