<div id="steps">

<!-- First Step Quick quote (MAKE DATA)-->
<div id="breadcrumb_info"></div>
	<div id="table_container">
		<!--Preloader-->
        <div id="preloader_cont">
			<div id="reman_preloader"></div>
		</div>
        <!--Group Selects-->
        <div id="group_select">
        	 <span class="label">Select Category:</span>	
			 <ul class="list">
                    <li class="cat_select" cat="T">AUTO TRANSMISSION</li>
                    <li class="cat_select" cat="X">TRANSFER CASE</li>
             </ul>
        </div>
        <!--Make Selection-->
		<div id="make_tbl" class="reman_hide">
			 <span class="label">Select Make:</span>	
			 <ul class="list">
			 <?php  foreach($this->getMake() as $index => $value): ?>
				<li class="make_select"  value="<?php echo $value['make_id']?>" startyear="<?php echo $value['start_year']?>" endyear="<?php echo $value['end_year']?>">
					<?php echo $value['make'] ?>
				</li>
			<?php $index +=1 ?>
			<?php if($index%25 == 0 && $index != 0): ?>
			</ul>
			<ul class="list">
			<?php endif; ?>			
			<?php endforeach; ?>
		
		</div>
		<!--Year Selection-->
		<div id="year_tbl" class="reman_hide">
			<span class="label">Select Production Year:</span>
		</div>   
		<!--Model Selection-->
		<div id="model_tbl" class="reman_hide">
			<span class="label">Select Model:</span>
		</div>
		<!--Parts Selection-->
		<div id="parts_tbl" class="reman_hide">
		</div>
		 
	</div>
    <!--Search Quote -->
	<div id="search_info">
		<span class="label">Custom Quote Details:</span>
		<table>
        	<tr>
            	<td class="headings">Part Number:</td>
                <td class="values" id="part_number_id"></td>
            </tr>
            <tr>
            	<td class="headings">Family:</td>
                <td class="values" id="part_family_id"></td>
            </tr>
            <tr style="height:40px;">
            	<td class="headings">MSRP:</td>
                <td class="values" id="part_msrp_id"></td>
            </tr>
            <tr>
            	<td style="color:#00F;" class="headings">Your Price:</td>
                <td class="values" id="part_price_id"></td>
            </tr>
            <tr>
            	<td class="headings">Core:</td>
                <td class="values" id="part_core_id"></td>
            </tr>
        </table>
		<div id="product_details_btn">
			<a href="#"><span>Start Over</span></a>
		</div>
        <!--Products Error-->
        <div class="product_error"></div>
		
	</div>
   
</div>