<?php
/**
 * Reman Shipping Estimate Template
 *
 * @category    Reman
 * @package     Design
 * @author		Igor Zhavoronkin (zhavoronkin.i@gmail.com)
 */
?>
<?php
	
	$_product = Mage::getModel('sync/applic')->loadProduct($this->getRequest()->getPost('id')); 
	//MKE Stock
	$mke = $_product->getData('parts_inventory_nc');
	//BWI Stock
	$bwi = $_product->getData('parts_inventory_ne');
	//ONT Stock
	$ont = $_product->getData('parts_inventory_sw');
	//ATL Stock
	$atl = $_product->getData('parts_inventory_se');
	
	$array = array();
	if($bwi != 0 && $bwi != null){
		array_push($array, "21113");
	}
	
	array_push($array, "53223");
	
	if($ont != 0 && $ont != null){	
		array_push($array, "91761");
	}
	if($atl != 0 && $atl != null){	
		array_push($array, "30344");
	}
?>


<div class="reman_preloader_shipping" style="display:none;"></div>
<div id="estimate-shipping">
	
	<div class="ship-to-zip">
 		<div class="heading">Shipping Details</div>
        <table>
        	<tr>
            	<td style="padding-right:5px;">Ship to Zip:</td>
                <td><input id="zip_value" value="" style="width:70px;" type="text" /></td>
            <tr>    
        </table>
        <button onclick='if($j("#zip_value").attr("value") != ""){estimateShipping(<?php echo json_encode($array); ?> , $j("#zip_value").attr("value"))}; return false;'>Submit</button> 
        
        
        <button onclick="resetShipping(); return false;">Cancel</button>
          
    </div>
    
    <div id="best-shipping" class="result-estimate" style="display:none;">
    	<table>
        	<tr>
            	<td style="font-size:17px; padding-top:15px;">Estimate Delivery Time:</td>
                <td id="shipping-result" style="font-size:17px; width:111px; font-weight:bold; padding-top:16px;"></td>
                <td style="width:90px;"><button style="margin-top:0px; height:40px;" onclick="Reman_QuickQuote.prototype.loadOrder(); return false;">Order</button></td>
            </tr>
        </table>
    </div>
    
    
    <div style="clear:both;"></div>
    <div id="best-carriers" class="result-estimate" style="display:none;">
    </div>
</div>

